# Generated by Django 6.0.3 on 2026-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedride',
            name='available_seats',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='sharedride',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
    ]
